import {useEffect,useMemo,useState} from 'react';
import AdminLayout,{EmptyState,StatCard,StatusBadge} from '../../components/admin/AdminLayout';
import {groupOrderRows,shortOrderReference} from '../../lib/orderGroups';

const money=value=>`${Number(value||0).toLocaleString('en-US')} MKD`;

export default function AdminCustomers(){
 const [orderRows,setOrderRows]=useState([]),[search,setSearch]=useState(''),[selected,setSelected]=useState(null),[error,setError]=useState('');
 useEffect(()=>{fetch('/api/orders').then(response=>{if(!response.ok)throw new Error();return response.json();}).then(data=>setOrderRows(Array.isArray(data)?data:[])).catch(()=>setError('Customers could not be loaded. Refresh and try again.'));},[]);
 useEffect(()=>{if(!selected)return;const close=event=>{if(event.key==='Escape')setSelected(null);};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[selected]);
 const customers=useMemo(()=>{const map=new Map();groupOrderRows(orderRows).forEach(order=>{const key=(order.customer_email||order.customer_phone||order.customer_name||'unknown').toLowerCase();const customer=map.get(key)||{key,name:order.customer_name||'Unknown customer',email:order.customer_email||'',phone:order.customer_phone||'',city:order.customer_city||'',orders:[],spent:0};customer.orders.push(order);if(order.status!=='cancelled')customer.spent+=Number(order.total||0);map.set(key,customer);});return [...map.values()].sort((a,b)=>b.spent-a.spent);},[orderRows]);
 const visible=customers.filter(customer=>`${customer.name} ${customer.email} ${customer.phone} ${customer.city}`.toLowerCase().includes(search.toLowerCase()));
 const repeat=customers.filter(customer=>customer.orders.length>1).length,average=customers.length?customers.reduce((sum,customer)=>sum+customer.spent,0)/customers.length:0;
 return <AdminLayout title="Customers">
  {error&&<div className="admin-alert" role="alert">{error}</div>}
  <div className="admin-grid-stats"><StatCard label="Customers" value={customers.length} detail="Unique customer profiles"/><StatCard label="Returning" value={repeat} detail="Placed more than one order" tone="green"/><StatCard label="Average value" value={money(average)} detail="Average spend per customer"/><StatCard label="Cities served" value={new Set(customers.map(customer=>customer.city).filter(Boolean)).size} detail="Delivery locations"/></div>
  <div className="admin-toolbar"><input className="admin-input" aria-label="Search customers" placeholder="Search name, email, phone, or city…" value={search} onChange={event=>setSearch(event.target.value)}/></div>
  <section className="admin-panel"><div className="admin-panel-head"><div><h2>Customer directory</h2><p>{visible.length} matching customers</p></div></div>{visible.length?<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Customer</th><th>Contact</th><th>City</th><th>Orders</th><th>Total spent</th><th></th></tr></thead><tbody>{visible.map(customer=><tr key={customer.key}><td><strong>{customer.name}</strong></td><td>{customer.email||'—'}<br/><small>{customer.phone||''}</small></td><td>{customer.city||'—'}</td><td>{customer.orders.length}</td><td><strong>{money(customer.spent)}</strong></td><td><button className="admin-button secondary" onClick={()=>setSelected(customer)}>View</button></td></tr>)}</tbody></table></div>:<EmptyState title="No customers found" text="Customers are created automatically when they place an order."/>}</section>
  {selected&&<div className="admin-modal" role="dialog" aria-modal="true" aria-labelledby="customer-title" onMouseDown={event=>{if(event.target===event.currentTarget)setSelected(null)}}><section className="admin-modal-card"><header className="admin-modal-head"><h2 id="customer-title">{selected.name}</h2><button aria-label="Close" onClick={()=>setSelected(null)}>×</button></header><div className="admin-modal-body"><div className="admin-form-grid" style={{marginBottom:20}}><div className="admin-field"><label>Email</label><span>{selected.email||'—'}</span></div><div className="admin-field"><label>Phone</label><span>{selected.phone||'—'}</span></div><div className="admin-field"><label>City</label><span>{selected.city||'—'}</span></div><div className="admin-field"><label>Lifetime value</label><strong>{money(selected.spent)}</strong></div></div><h3 style={{fontSize:14,textTransform:'uppercase'}}>Order history</h3><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Order</th><th>Items</th><th>Total</th><th>Status</th></tr></thead><tbody>{selected.orders.map(order=><tr key={order.key}><td>#{shortOrderReference(order)}</td><td>{order.items.length} {order.items.length===1?'item':'items'}</td><td>{money(order.total)}</td><td><StatusBadge status={order.status}/></td></tr>)}</tbody></table></div></div></section></div>}
 </AdminLayout>;
}
