import { useEffect, useMemo, useState } from 'react';
import AdminLayout, { EmptyState, StatCard, StatusBadge } from '../../components/admin/AdminLayout';

const STATUSES = ['pending','confirmed','processing','shipped','delivered','cancelled'];
const money = (value) => `${Number(value || 0).toLocaleString('en-US')} MKD`;

export default function AdminOrders() {
  const [orders,setOrders]=useState([]); const [filter,setFilter]=useState('all'); const [search,setSearch]=useState(''); const [selected,setSelected]=useState(null); const [error,setError]=useState('');
  const load=async()=>{try{const response=await fetch('/api/orders');if(!response.ok)throw new Error();const data=await response.json();setOrders(Array.isArray(data)?data:[]);}catch{setError('Orders could not be loaded. Please refresh and try again.');}};
  useEffect(()=>{load();},[]);
  const updateStatus=async(id,status)=>{const response=await fetch('/api/orders',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,status})});if(!response.ok){setError('The order status could not be updated.');return;}setOrders((current)=>current.map((order)=>order.id===id?{...order,status}:order));setSelected((order)=>order?.id===id?{...order,status}:order);};
  const visible=useMemo(()=>orders.filter((order)=>{const matchesStatus=filter==='all'||(order.status||'pending')===filter;const haystack=`${order.id} ${order.customer_name} ${order.customer_email} ${order.customer_phone} ${order.product_name} ${order.product_sku}`.toLowerCase();return matchesStatus&&haystack.includes(search.toLowerCase());}),[orders,filter,search]);
  const revenue=orders.filter((order)=>order.status!=='cancelled').reduce((sum,order)=>sum+Number(order.total||0),0);
  return <AdminLayout title="Orders" action={<button className="admin-button secondary" onClick={load}>Refresh</button>}>
    {error&&<div className="admin-alert">{error}</div>}
    <div className="admin-grid-stats"><StatCard label="All orders" value={orders.length} detail="Complete order history"/><StatCard label="Needs attention" value={orders.filter((o)=>['pending','confirmed','processing'].includes(o.status||'pending')).length} detail="Not shipped yet" tone="orange"/><StatCard label="Shipped" value={orders.filter((o)=>o.status==='shipped').length} detail="On the way to customers"/><StatCard label="Sales value" value={money(revenue)} detail="Excludes cancelled orders" tone="green"/></div>
    <div className="admin-toolbar"><input className="admin-input" placeholder="Search order, customer, phone, SKU…" value={search} onChange={(event)=>setSearch(event.target.value)}/><select className="admin-select" value={filter} onChange={(event)=>setFilter(event.target.value)}><option value="all">All statuses</option>{STATUSES.map((status)=><option key={status} value={status}>{status[0].toUpperCase()+status.slice(1)}</option>)}</select></div>
    <section className="admin-panel"><div className="admin-panel-head"><div><h2>Order list</h2><p>{visible.length} matching orders</p></div></div>{visible.length?<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Order</th><th>Customer</th><th>Item</th><th>Total</th><th>Status</th><th></th></tr></thead><tbody>{visible.map((order)=><tr key={order.id}><td><strong>#{order.id}</strong><br/><small>{order.created_at?new Date(order.created_at).toLocaleDateString('en-GB'):'—'}</small></td><td><strong>{order.customer_name||'—'}</strong><br/><small>{order.customer_city||''}</small></td><td>{order.product_name||'Product'}<br/><small>{order.size?`Size ${order.size}`:''} · Qty {order.quantity||1}</small></td><td><strong>{money(order.total)}</strong></td><td><StatusBadge status={order.status}/></td><td><button className="admin-button secondary" onClick={()=>setSelected(order)}>Open</button></td></tr>)}</tbody></table></div>:<EmptyState title="No matching orders" text="Try a different search or status filter."/>}</section>
    {selected&&<div className="admin-modal" onMouseDown={(event)=>{if(event.target===event.currentTarget)setSelected(null)}}><section className="admin-modal-card"><header className="admin-modal-head"><h2>Order #{selected.id}</h2><button aria-label="Close" onClick={()=>setSelected(null)}>×</button></header><div className="admin-modal-body"><div className="admin-form-grid"><div className="admin-field"><label>Customer</label><strong>{selected.customer_name||'—'}</strong></div><div className="admin-field"><label>Phone</label><span>{selected.customer_phone||'—'}</span></div><div className="admin-field"><label>Email</label><span>{selected.customer_email||'—'}</span></div><div className="admin-field"><label>Delivery address</label><span>{[selected.customer_address,selected.customer_city].filter(Boolean).join(', ')||'—'}</span></div><div className="admin-field"><label>Product</label><span>{selected.product_brand} {selected.product_name}<br/>SKU {selected.product_sku||'—'} · Size {selected.size||'—'} · Qty {selected.quantity||1}</span></div><div className="admin-field"><label>Total / payment</label><strong>{money(selected.total)}</strong><span>Cash on delivery</span></div><div className="admin-field wide"><label>Update status</label><select className="admin-select" value={selected.status||'pending'} onChange={(event)=>updateStatus(selected.id,event.target.value)}>{STATUSES.map((status)=><option key={status} value={status}>{status[0].toUpperCase()+status.slice(1)}</option>)}</select></div></div></div></section></div>}
  </AdminLayout>;
}
