import {useEffect,useMemo,useState} from 'react';
import AdminLayout,{EmptyState,StatCard,StatusBadge} from '../../components/admin/AdminLayout';
import {groupOrderRows,shortOrderReference} from '../../lib/orderGroups';

const STATUSES=['pending','confirmed','processing','shipped','delivered','cancelled'];
const money=value=>`${Number(value||0).toLocaleString('en-US')} MKD`;

export default function AdminOrders(){
 const [orderRows,setOrderRows]=useState([]),[filter,setFilter]=useState('all'),[search,setSearch]=useState(''),[selected,setSelected]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[saving,setSaving]=useState(false);
 const orders=useMemo(()=>groupOrderRows(orderRows),[orderRows]);
 const load=async()=>{setError('');try{const response=await fetch('/api/orders');if(!response.ok)throw new Error();const data=await response.json();setOrderRows(Array.isArray(data)?data:[]);}catch{setError('Orders could not be loaded. Please refresh and try again.');}};
 useEffect(()=>{load();},[]);
 useEffect(()=>{if(!selected)return;const close=event=>{if(event.key==='Escape')setSelected(null);};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[selected]);
 const updateStatus=async(id,status)=>{setError('');setNotice('');setSaving(true);try{const response=await fetch('/api/orders',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,status})});const data=await response.json();if(!response.ok)throw new Error(data.error||'The order status could not be updated.');const active=orders.find(order=>order.id===id);setOrderRows(current=>current.map(row=>row.id===id||(active?.checkout_id&&row.checkout_id===active.checkout_id)?{...row,status}:row));setSelected(order=>order?.id===id?{...order,status,items:order.items.map(item=>({...item,status}))}:order);if(['shipped','delivered'].includes(status))setNotice(data.emailNotification==='sent'?`Status saved and the customer’s ${status} email was sent.`:data.emailNotification==='not-configured'?`Status saved. Customer email is not configured yet.`:`Status saved, but the customer email failed. Contact the customer another way.`);else setNotice('Order status saved.');}catch(err){setError(err.message||'The order status could not be updated.');}finally{setSaving(false);}};
 const visible=useMemo(()=>orders.filter(order=>{const matchesStatus=filter==='all'||(order.status||'pending')===filter;const items=order.items.map(item=>`${item.product_brand} ${item.product_name} ${item.product_sku} ${item.size}`).join(' ');const haystack=`${order.reference} ${order.customer_name} ${order.customer_email} ${order.customer_phone} ${items}`.toLowerCase();return matchesStatus&&haystack.includes(search.toLowerCase());}),[orders,filter,search]);
 const revenue=orders.filter(order=>order.status!=='cancelled').reduce((sum,order)=>sum+Number(order.total||0),0);
 return <AdminLayout title="Orders" action={<button className="admin-button secondary" onClick={load}>Refresh</button>}>
  {error&&<div className="admin-alert" role="alert">{error}</div>}{notice&&<div className="admin-alert success" role="status">{notice}</div>}
  <div className="admin-grid-stats"><StatCard label="All orders" value={orders.length} detail="Complete order history"/><StatCard label="Needs attention" value={orders.filter(order=>['pending','confirmed','processing'].includes(order.status||'pending')).length} detail="Not shipped yet" tone="orange"/><StatCard label="Shipped" value={orders.filter(order=>order.status==='shipped').length} detail="On the way to customers"/><StatCard label="Sales value" value={money(revenue)} detail="Excludes cancelled orders" tone="green"/></div>
  <div className="admin-toolbar"><input className="admin-input" aria-label="Search orders" placeholder="Search order, customer, phone, SKU…" value={search} onChange={event=>setSearch(event.target.value)}/><select className="admin-select" aria-label="Filter order status" value={filter} onChange={event=>setFilter(event.target.value)}><option value="all">All statuses</option>{STATUSES.map(status=><option key={status} value={status}>{status[0].toUpperCase()+status.slice(1)}</option>)}</select></div>
  <section className="admin-panel"><div className="admin-panel-head"><div><h2>Order list</h2><p>{visible.length} matching orders</p></div></div>{visible.length?<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Order</th><th>Customer</th><th>Items</th><th>Total</th><th>Status</th><th></th></tr></thead><tbody>{visible.map(order=><tr key={order.key}><td><strong>#{shortOrderReference(order)}</strong><br/><small>{order.created_at?new Date(order.created_at).toLocaleDateString('en-GB'):'—'}</small></td><td><strong>{order.customer_name||'—'}</strong><br/><small>{order.customer_city||''}</small></td><td>{order.items[0]?.product_name||'Product'}<br/><small>{order.items.length} {order.items.length===1?'item':'items'}</small></td><td><strong>{money(order.total)}</strong></td><td><StatusBadge status={order.status}/></td><td><button className="admin-button secondary" onClick={()=>setSelected(order)}>Open</button></td></tr>)}</tbody></table></div>:<EmptyState title="No matching orders" text="Try a different search or status filter."/>}</section>
  {selected&&<div className="admin-modal" role="dialog" aria-modal="true" aria-labelledby="order-title" onMouseDown={event=>{if(event.target===event.currentTarget)setSelected(null)}}><section className="admin-modal-card"><header className="admin-modal-head"><h2 id="order-title">Order #{shortOrderReference(selected)}</h2><button aria-label="Close" onClick={()=>setSelected(null)}>×</button></header><div className="admin-modal-body"><div className="admin-form-grid"><div className="admin-field"><label>Customer</label><strong>{selected.customer_name||'—'}</strong></div><div className="admin-field"><label>Phone</label><span>{selected.customer_phone||'—'}</span></div><div className="admin-field"><label>Email</label><span>{selected.customer_email||'—'}</span></div><div className="admin-field"><label>Delivery address</label><span>{[selected.customer_address,selected.customer_city].filter(Boolean).join(', ')||'—'}</span></div><div className="admin-field wide"><label>Products</label>{selected.items.map(item=><span key={item.id}>{item.product_brand} {item.product_name} · SKU {item.product_sku||'—'} · Size {item.size||'—'} · Qty {item.quantity||1}</span>)}</div><div className="admin-field"><label>Total / payment</label><strong>{money(selected.total)}</strong><span>Cash on delivery</span></div><div className="admin-field wide"><label htmlFor="order-status">Update status</label><select id="order-status" className="admin-select" disabled={saving} value={selected.status||'pending'} onChange={event=>updateStatus(selected.id,event.target.value)}>{STATUSES.map(status=><option key={status} value={status}>{status[0].toUpperCase()+status.slice(1)}</option>)}</select></div></div></div></section></div>}
 </AdminLayout>;
}
