import { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/router';
import { adminRequest } from '../../lib/adminRequest';
import AdminLayout, { EmptyState, StatCard } from '../../components/admin/AdminLayout';

const blank={brand:'',name:'',sku:'',category:'Shoes',subcategory:'',gender:'Men',oldPrice:'',newPrice:'',color:'',description:'',images:[],sizes:[{size:'',stock:0}],featured:false,inStock:true};
const totalStock=(product)=>(product.sizes||[]).reduce((sum,size)=>sum+Number(size.stock||0),0);

export default function AdminProducts(){
  const router=useRouter();const[products,setProducts]=useState([]);const[form,setForm]=useState(blank);const[editing,setEditing]=useState(null);const[open,setOpen]=useState(false);const[search,setSearch]=useState('');const[stock,setStock]=useState('all');const[category,setCategory]=useState('all');const[saving,setSaving]=useState(false);const[uploading,setUploading]=useState(false);const[message,setMessage]=useState('');
  const load=async()=>{try{setProducts(await adminRequest('/api/admin/products'));}catch(error){setMessage(error.message);}};
  useEffect(()=>{load();},[]);useEffect(()=>{if(router.query.search)setSearch(String(router.query.search));},[router.query.search]);
  const categories=[...new Set(products.map((p)=>p.category).filter(Boolean))];
  const visible=useMemo(()=>products.filter((product)=>{const q=search.toLowerCase();const matches=`${product.name} ${product.brand} ${product.sku}`.toLowerCase().includes(q);const qty=totalStock(product);return matches&&(category==='all'||product.category===category)&&(stock==='all'||(stock==='low'&&qty>0&&qty<=5)||(stock==='out'&&qty===0)||(stock==='available'&&qty>5));}),[products,search,category,stock]);
  const startAdd=()=>{setEditing(null);setForm(blank);setOpen(true);};
  const startEdit=(product)=>{setEditing(product);setForm({...blank,...product,images:product.images||[],sizes:product.sizes?.length?product.sizes:[{size:'',stock:0}]});setOpen(true);};
  const upload=async(event)=>{const file=event.target.files?.[0];if(!file)return;if(file.size>4*1024*1024){setMessage('Choose an image under 4 MB.');return;}setUploading(true);try{const body=new FormData();body.append('file',file);const data=await adminRequest('/api/admin/upload',{method:'POST',body});setForm(current=>({...current,images:[...current.images,data.url]}));}catch(error){setMessage(error.message);}finally{setUploading(false);}};
  const save=async(event)=>{event.preventDefault();setSaving(true);setMessage('');try{const payload={...form,oldPrice:Number(form.oldPrice),newPrice:Number(form.newPrice)};await adminRequest('/api/admin/products',{method:editing?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});await load();setOpen(false);setMessage(editing?'Product updated.':'Product added.');}catch(error){setMessage(error.message);}finally{setSaving(false);}};
  const remove=async(product)=>{if(!window.confirm('Delete this product from the catalogue?'))return;try{await adminRequest('/api/admin/products',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:product.id,_revision:product._revision})});await load();}catch(error){setMessage(error.message);}};
  const updateSize=(index,key,value)=>setForm((current)=>({...current,sizes:current.sizes.map((size,i)=>i===index?{...size,[key]:key==='stock'?Number(value):value}:size)}));
  return <AdminLayout title="Products & stock" action={<button className="admin-button red" onClick={startAdd}>+ Add product</button>}>
    {message&&<div className={`admin-alert ${message.includes('updated')||message.includes('added')?'admin-success':''}`}>{message}</div>}
    <div className="admin-grid-stats"><StatCard label="Products" value={products.length} detail="Published catalogue"/><StatCard label="Units in stock" value={products.reduce((sum,p)=>sum+totalStock(p),0)} detail="Across all sizes" tone="green"/><StatCard label="Low stock" value={products.filter((p)=>totalStock(p)>0&&totalStock(p)<=5).length} detail="Five units or fewer" tone="orange"/><StatCard label="Out of stock" value={products.filter((p)=>totalStock(p)===0).length} detail="Needs attention" tone="red"/></div>
    <div className="admin-toolbar"><input className="admin-input" placeholder="Search name, brand, or SKU…" value={search} onChange={(e)=>setSearch(e.target.value)}/><select className="admin-select" value={category} onChange={(e)=>setCategory(e.target.value)}><option value="all">All categories</option>{categories.map((item)=><option key={item}>{item}</option>)}</select><select className="admin-select" value={stock} onChange={(e)=>setStock(e.target.value)}><option value="all">All stock</option><option value="available">Well stocked</option><option value="low">Low stock</option><option value="out">Out of stock</option></select></div>
    <section className="admin-panel"><div className="admin-panel-head"><div><h2>Catalogue</h2><p>{visible.length} matching products</p></div></div>{visible.length?<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Product</th><th>Category</th><th>Price</th><th>Sizes</th><th>Stock</th><th></th></tr></thead><tbody>{visible.map((product)=>{const qty=totalStock(product);return <tr key={product.id}><td><div style={{display:'flex',gap:12,alignItems:'center'}}><img src={product.images?.[0]} alt="" style={{width:54,height:54,objectFit:'contain',background:'#f4f4f4'}}/><span><strong style={{textTransform:'uppercase'}}>{product.name}</strong><br/><small>{product.brand} · {product.sku||'No SKU'}</small></span></div></td><td>{product.category}<br/><small>{product.gender}</small></td><td><strong>{Number(product.newPrice).toLocaleString()} MKD</strong><br/><small>{product.discount||0}% off</small></td><td>{(product.sizes||[]).map((size)=>size.size).filter(Boolean).join(', ')||'—'}</td><td><strong style={{color:qty===0?'#c82027':qty<=5?'#d66b10':'#17724a'}}>{qty}</strong></td><td><div style={{display:'flex',gap:7}}><button className="admin-button secondary" onClick={()=>startEdit(product)}>Edit</button><button className="admin-button danger" onClick={()=>remove(product)}>Delete</button></div></td></tr>})}</tbody></table></div>:<EmptyState title="No matching products" text="Change the filters or add a new product." action={<button className="admin-button red" onClick={startAdd}>Add product</button>}/>}</section>
    {open&&<div className="admin-modal"><form className="admin-modal-card" onSubmit={save}><header className="admin-modal-head"><h2>{editing?'Edit product':'Add product'}</h2><button type="button" aria-label="Close" onClick={()=>setOpen(false)}>×</button></header><div className="admin-modal-body">{message&&<p role="alert" className="admin-alert">{message}</p>}<div className="admin-form-grid">
      {[['Brand','brand'],['Product name','name'],['SKU','sku'],['Subcategory','subcategory'],['Color','color']].map(([label,key])=><div className="admin-field" key={key}><label>{label}{['brand','name','sku'].includes(key)?' *':''}</label><input className="admin-input" required={['brand','name','sku'].includes(key)} value={form[key]} onChange={(e)=>setForm({...form,[key]:e.target.value})}/></div>)}
      <div className="admin-field"><label>Category</label><select className="admin-select" value={form.category} onChange={(e)=>setForm({...form,category:e.target.value})}><option>Shoes</option><option>Clothing</option><option>Accessories</option></select></div><div className="admin-field"><label>Customer group</label><select className="admin-select" value={form.gender} onChange={(e)=>setForm({...form,gender:e.target.value})}><option>Men</option><option>Women</option><option>Kids</option><option>Unisex</option></select></div><div className="admin-field"><label>Original price (MKD)</label><input className="admin-input" type="number" min="0" required value={form.oldPrice} onChange={(e)=>setForm({...form,oldPrice:e.target.value})}/></div><div className="admin-field"><label>Outlet price (MKD)</label><input className="admin-input" type="number" min="0" required value={form.newPrice} onChange={(e)=>setForm({...form,newPrice:e.target.value})}/></div><div className="admin-field wide"><label>Description</label><textarea className="admin-textarea" rows="4" value={form.description} onChange={(e)=>setForm({...form,description:e.target.value})}/></div>
      <div className="admin-field wide"><label>Product images</label><input className="admin-input" type="file" accept="image/jpeg,image/png,image/webp" onChange={upload} disabled={uploading}/>{uploading&&<span>Uploading image…</span>}{form.images.length>0&&<div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{form.images.map((image,index)=><div key={image} style={{position:'relative'}}><img src={image} alt="" style={{width:72,height:72,objectFit:'contain',border:'1px solid #ddd'}}/><button type="button" aria-label="Remove image" onClick={()=>setForm({...form,images:form.images.filter((_,i)=>i!==index)})} style={{position:'absolute',top:-6,right:-6,border:0,borderRadius:'50%',background:'#111',color:'#fff',width:20,height:20}}>×</button></div>)}</div>}</div>
      <div className="admin-field wide"><label>Sizes and stock</label>{form.sizes.map((size,index)=><div key={index} style={{display:'grid',gridTemplateColumns:'1fr 1fr auto',gap:8,marginBottom:8}}><input className="admin-input" placeholder="Size (e.g. 42)" value={size.size} onChange={(e)=>updateSize(index,'size',e.target.value)} required/><input className="admin-input" type="number" min="0" placeholder="Quantity" value={size.stock} onChange={(e)=>updateSize(index,'stock',e.target.value)}/><button className="admin-button danger" type="button" disabled={form.sizes.length===1} onClick={()=>setForm({...form,sizes:form.sizes.filter((_,i)=>i!==index)})}>×</button></div>)}<button className="admin-button secondary" type="button" onClick={()=>setForm({...form,sizes:[...form.sizes,{size:'',stock:0}]})}>+ Add size</button></div><label style={{display:'flex',gap:9,alignItems:'center',fontSize:12}}><input type="checkbox" checked={form.featured} onChange={(e)=>setForm({...form,featured:e.target.checked})}/> Feature this product on the homepage</label>
    </div><div style={{display:'flex',justifyContent:'flex-end',gap:9,marginTop:24}}><button className="admin-button secondary" type="button" onClick={()=>setOpen(false)}>Cancel</button><button className="admin-button red" disabled={saving||uploading}>{saving?'Saving…':'Save product'}</button></div></div></form></div>}
  </AdminLayout>;
}
