-- Run once in the SQL Editor of the existing OutletX Supabase project.
-- Additive setup: existing orders and existing catalogue entries are preserved.
begin;
create table if not exists public.outletx_products (
  id bigint generated by default as identity (start with 100000) primary key,
  data jsonb not null,
  revision integer not null default 1 check (revision > 0)
);
create table if not exists public.outletx_content (
  id text primary key,
  data jsonb not null,
  revision integer not null default 1 check (revision > 0)
);
create table if not exists public.outletx_order_lines (
  id uuid primary key default gen_random_uuid(),
  checkout_id uuid not null,
  line_index integer not null check (line_index >= 0),
  request_hash text not null,
  created_at timestamptz not null default now(),
  product_name text not null,
  product_brand text not null,
  product_sku text not null,
  product_price numeric not null check (product_price >= 0),
  size text not null,
  quantity integer not null check (quantity > 0),
  total numeric not null check (total >= 0),
  customer_name text not null,
  customer_phone text not null,
  customer_email text not null,
  customer_city text not null,
  customer_address text not null,
  customer_notes text not null default '',
  status text not null default 'pending' check (status in ('pending','confirmed','processing','shipped','delivered','cancelled')),
  unique (checkout_id, line_index)
);
alter table public.outletx_products enable row level security;
alter table public.outletx_content enable row level security;
alter table public.outletx_order_lines enable row level security;
revoke all on public.outletx_products, public.outletx_content, public.outletx_order_lines from anon, authenticated;
grant all on public.outletx_products, public.outletx_content, public.outletx_order_lines to service_role;
grant usage, select on sequence public.outletx_products_id_seq to service_role;
create index if not exists outletx_order_lines_created_at_idx on public.outletx_order_lines(created_at desc);
insert into public.outletx_products(id, data) values (1, '{"brand":"Adidas","name":"UltraRun 5 ","sku":"JQ0019","category":"Shoes","subcategory":"Running","gender":"Men","ageGroup":null,"oldPrice":4990,"newPrice":2990,"color":"Neon","description":"","images":["/images/products/1782507220334_maratonki-adidas-ultrarun-5-tr-jq0019-2.jpg"],"sizes":[{"size":"42","stock":3},{"size":"43","stock":2},{"size":"44","stock":2}],"discount":40,"inStock":true,"featured":true}'::jsonb) on conflict (id) do nothing;
insert into public.outletx_products(id, data) values (2, '{"brand":"Adidas","name":"VL COURT BOLD","sku":" IH9152","category":"Shoes","subcategory":"Lifestyle","gender":"Women","ageGroup":null,"oldPrice":3990,"newPrice":2990,"color":"Brown/Pink","description":"","images":["/images/products/1782508670275_669261.jpg"],"sizes":[{"size":"35","stock":2},{"size":"36","stock":2},{"size":"37","stock":3},{"size":"38","stock":3},{"size":"39","stock":2}],"discount":25,"inStock":true,"featured":true}'::jsonb) on conflict (id) do nothing;
insert into public.outletx_products(id, data) values (3, '{"brand":"ADIDAS","name":"VL COURT BOLD JR","sku":"IH4780","category":"Shoes","subcategory":"Lifestyle","gender":"Women","ageGroup":null,"oldPrice":3990,"newPrice":2990,"color":"Red","description":"","images":["/images/products/1782508962810_buty-mlodziezowe-adidas-court-bold-bordowe-ih4780-skorzane-sportowe-36-b-iext187545553.jpg"],"sizes":[{"size":"38","stock":2},{"size":"39","stock":3},{"size":"37","stock":2},{"size":"36","stock":3}],"discount":25,"inStock":true,"featured":true}'::jsonb) on conflict (id) do nothing;
insert into public.outletx_content(id, data) values ('main', '{"slides":[{"image":"/images/products/7cb29c20-38f9-4025-9e04-4d1c1b3ac7e4.png","title":"BRANDED SPORTSWEAR.","subtitle":"OUTLET PRICES.","tag":"Dua Mall, Struga — Outlet Store","description":"Authentic branded sportswear at outlet prices, with discounts up to 70%.","link":"/products","linkText":"Shop all deals","link2":"/products?gender=men","linkText2":"Men","link3":"/products?gender=women","linkText3":"Women"},{"image":"https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=1400&h=700&fit=crop","title":"NEW COLLECTION.","subtitle":"JUST LANDED.","tag":"Fresh stock — Limited quantities","description":"Explore the latest arrivals in footwear, clothing, and accessories.","link":"/products","linkText":"Shop new","link2":"/products?category=shoes","linkText2":"Shoes","link3":"/products?gender=kids","linkText3":"Kids"},{"image":"https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=1400&h=700&fit=crop","title":"UP TO 70% OFF.","subtitle":"OUTLET DEALS.","tag":"Limited time","description":"Discover the biggest current discounts across authentic brands.","link":"/products?sort=discount","linkText":"Shop sale","link2":"/products?gender=women","linkText2":"Women","link3":"/products?gender=men","linkText3":"Men"}],"settings":{"instagram":"@OutletXstruga","address":"Dua Mall, Struga","country":"North Macedonia","deliveryFee":150,"freeDeliveryOver":3000,"openingHours":{"weekdays":"09:00 - 21:00","sunday":"10:00 - 20:00"}}}'::jsonb) on conflict (id) do nothing;
-- Only product photographs go in this public bucket. No customer data or documents.
insert into storage.buckets(id, name, public, file_size_limit, allowed_mime_types)
values ('outletx-product-images','outletx-product-images',true,4194304,array['image/jpeg','image/png','image/webp'])
on conflict (id) do nothing;
commit;
