import SiteLink from '../components/SiteLink';
import Seo from '../components/Seo';
import StoreLayout from '../components/store/StoreLayout';
import {useStore} from '../context/StoreContext';
import {useLanguage} from '../context/LanguageContext';
export {getStorePageProps as getStaticProps} from '../lib/storePage';
const copy={
 en:{eyebrow:'A local store in Struga',title:<>Good shoes.<br/><span>Better prices.</span></>,intro:'OutletX is a footwear store at Dua Mall, built around limited branded stock, visible availability and straightforward outlet prices.',h2:'Online shopping with a real store behind it',p1:'The website lets you see the styles and sizes currently listed before visiting or ordering. Each product has a code, current price and its available sizes.',p2:'Outlet stock changes. When a size is gone it may not return, so the catalogue focuses on what is available now instead of promising an endless range.',values:[['Clear product information','Price, product code and available sizes are shown together.'],['Local help','Visit the store or ask about a product and fit through @OutletXstruga.'],['No card details','Online orders use cash on delivery; this website does not collect card information.']],visit:'Try them on in Struga',shop:'Shop the collection',details:'Contact & directions'},
 mk:{eyebrow:'Локална продавница во Струга',title:<>Добри обувки.<br/><span>Подобри цени.</span></>,intro:'OutletX е продавница за обувки во Dua Mall, со ограничена брендирана залиха, јасна достапност и едноставни outlet цени.',h2:'Онлајн купување со вистинска продавница зад него',p1:'На страницата можете да ги видите моделите и големините пред посета или нарачка. Секој производ има шифра, цена и достапни големини.',p2:'Outlet залихата се менува. Кога големината ќе се продаде можеби нема да се врати, па каталогот го прикажува она што е достапно сега.',values:[['Јасни информации','Цената, шифрата и големините се прикажани заедно.'],['Локална помош','Посетете нè или прашајте за производ и големина преку @OutletXstruga.'],['Без податоци од картичка','Онлајн нарачките се плаќаат при достава; страницата не собира податоци од картичка.']],visit:'Пробајте ги во Струга',shop:'Разгледај ја колекцијата',details:'Контакт и насоки'},
 sq:{eyebrow:'Dyqan lokal në Strugë',title:<>Këpucë të mira.<br/><span>Çmime më të mira.</span></>,intro:'OutletX është dyqan këpucësh në Dua Mall, me stok të kufizuar të markave, disponueshmëri të qartë dhe çmime outlet.',h2:'Blerje online me një dyqan të vërtetë pas saj',p1:'Faqja ju lejon të shihni modelet dhe madhësitë para vizitës ose porosisë. Çdo produkt ka kodin, çmimin dhe madhësitë në dispozicion.',p2:'Stoku outlet ndryshon. Kur një madhësi mbaron, mund të mos kthehet, prandaj katalogu tregon atë që është në dispozicion tani.',values:[['Informacion i qartë','Çmimi, kodi dhe madhësitë shfaqen së bashku.'],['Ndihmë lokale','Na vizitoni ose pyesni për produktin dhe madhësinë në @OutletXstruga.'],['Pa të dhëna karte','Porositë paguhen në dorëzim; faqja nuk mbledh të dhëna karte.']],visit:'Provojini në Strugë',shop:'Shfleto koleksionin',details:'Kontakt dhe udhëzime'}
};
export default function About(){const {content}=useStore(),{lang}=useLanguage(),c=copy[lang],s=content.settings;return <StoreLayout><Seo title="About OutletX | Dua Mall, Struga" description="Meet OutletX, the footwear store at Dua Mall, Struga." path="/about"/><section className="info-hero"><div><p className="store-eyebrow">{c.eyebrow}</p><h1>{c.title}</h1><p>{c.intro}</p></div></section><section className="store-section"><div className="info-story"><div><p className="store-eyebrow">OUTLETX · STRUGA</p><h2 className="store-title">{c.h2}</h2></div><div><p>{c.p1}</p><p>{c.p2}</p></div></div></section><section className="info-values">{c.values.map(([h,p],i)=><article key={h}><b>0{i+1}</b><h3>{h}</h3><p>{p}</p></article>)}</section><section className="info-visit"><div><p className="store-eyebrow">{s.address}</p><h2>{c.visit}</h2><p>Mon–Sat {s.openingHours.weekdays}<br/>Sunday {s.openingHours.sunday}</p><div><SiteLink className="store-button" href="/products">{c.shop}</SiteLink><SiteLink className="store-button light" href="/contact">{c.details}</SiteLink></div></div><iframe title="OutletX location" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d187.6620743480383!2d20.675127836415925!3d41.187039407592515!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1350e749a513feff%3A0xc0d3f98c173d96b8!2sOutlet%20X!5e0!3m2!1sen!2smk!4v1782426661903!5m2!1sen!2smk" loading="lazy" referrerPolicy="no-referrer-when-downgrade"/></section></StoreLayout>;}
