import SiteLink from '../components/SiteLink';
import Seo from '../components/Seo';
import StoreLayout from '../components/store/StoreLayout';
import {useStore} from '../context/StoreContext';
import {useLanguage} from '../context/LanguageContext';
export {getStorePageProps as getStaticProps} from '../lib/storePage';
const copy={
 en:{eye:'Help from a real store',title:<>Visit us.<br/>Ask us.</>,intro:'For product, size, delivery or order questions, use the official OutletX Instagram account or visit us in Struga.',location:'Store location',directions:'Open in Google Maps',social:'Official Instagram',socialP:'Use this account for product and order questions. Include your order reference when you have one.',message:'Open Instagram',hours:'Opening hours',every:'Open every day',support:'Why there is no contact form yet',supportP:'A public support email has not been approved. We will add a proper contact form only when there is a confirmed inbox and privacy process behind it. For now, Instagram and the physical store are the official contact options.'},
 mk:{eye:'Помош од вистинска продавница',title:<>Посетете нè.<br/>Прашајте нè.</>,intro:'За прашања за производ, големина, достава или нарачка, пишете на официјалниот Instagram или посетете нè во Струга.',location:'Локација',directions:'Отвори во Google Maps',social:'Официјален Instagram',socialP:'Користете го профилот за прашања за производ и нарачка. Наведете ја референцата ако ја имате.',message:'Отвори Instagram',hours:'Работно време',every:'Отворено секој ден',support:'Зошто сè уште нема контакт-форма',supportP:'Јавна е-пошта за поддршка сè уште не е одобрена. Ќе додадеме форма кога ќе има потврдено сандаче и процес за приватност. Дотогаш, Instagram и продавницата се официјалните опции.'},
 sq:{eye:'Ndihmë nga një dyqan i vërtetë',title:<>Na vizitoni.<br/>Na pyesni.</>,intro:'Për pyetje rreth produktit, madhësisë, dërgesës ose porosisë, përdorni Instagramin zyrtar ose na vizitoni në Strugë.',location:'Vendndodhja',directions:'Hap në Google Maps',social:'Instagrami zyrtar',socialP:'Përdoreni për pyetje rreth produktit dhe porosisë. Përfshini referencën kur e keni.',message:'Hap Instagramin',hours:'Orari',every:'Hapur çdo ditë',support:'Pse nuk ka ende formular kontakti',supportP:'Një email publik mbështetës nuk është miratuar. Formularin do ta shtojmë vetëm kur të ketë kuti postare dhe proces privatësie pas tij. Deri atëherë, Instagrami dhe dyqani janë opsionet zyrtare.'}
};
export default function Contact(){const {content}=useStore(),{lang}=useLanguage(),s=content.settings,c=copy[lang];const instagram='https://instagram.com/'+s.instagram.replace(/^@/,'');return <StoreLayout><Seo title="Contact OutletX | Dua Mall, Struga" description="Visit OutletX at Dua Mall, Struga or contact @OutletXstruga." path="/contact"/><section className="contact-hero"><div><p className="store-eyebrow">{c.eye}</p><h1>{c.title}</h1><p>{c.intro}</p></div></section><section className="contact-grid-new"><article id="location"><p className="store-eyebrow">{c.location}</p><h2>{s.address}</h2><p>{s.country}</p><SiteLink href="https://www.google.com/maps/search/?api=1&query=Outlet+X+Dua+Mall+Struga" target="_blank" rel="noopener noreferrer">{c.directions} ↗</SiteLink></article><article><p className="store-eyebrow">{c.social}</p><h2>{s.instagram}</h2><p>{c.socialP}</p><SiteLink href={instagram} target="_blank" rel="noopener noreferrer">{c.message} ↗</SiteLink></article><article id="hours"><p className="store-eyebrow">{c.hours}</p><h2>{c.every}</h2><p>Mon–Sat: {s.openingHours.weekdays}<br/>Sunday: {s.openingHours.sunday}</p></article></section><section className="contact-support-note"><h2>{c.support}</h2><p>{c.supportP}</p></section><section className="contact-map-new"><iframe title="OutletX location in Dua Mall, Struga" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d187.6620743480383!2d20.675127836415925!3d41.187039407592515!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1350e749a513feff%3A0xc0d3f98c173d96b8!2sOutlet%20X!5e0!3m2!1sen!2smk!4v1782426661903!5m2!1sen!2smk" loading="lazy" referrerPolicy="no-referrer-when-downgrade"/></section></StoreLayout>;}
