import InfoPage from '../components/InfoPage';
import SiteLink from '../components/SiteLink';
const title={en:'Help & FAQ',mk:'Помош и чести прашања',sq:'Ndihmë dhe pyetje'};
const description={en:'Quick answers about products, sizing, ordering and visiting OutletX.',mk:'Брзи одговори за производи, големини, нарачки и посета на OutletX.',sq:'Përgjigje të shpejta për produktet, madhësitë, porositë dhe vizitën në OutletX.'};
const q={
 en:[['Are the sizes on the website live?','Product pages show the latest availability we have. Stock is limited and adding an item to your bag does not reserve it. Availability is checked again when you order.'],['How do I choose a size?','Open the size guide, compare a shoe you already own, or send the product code and your usual size to OutletX on Instagram.'],['How do I pay?','Payment is cash on delivery. This website never asks for card details.'],['What does delivery cost?','Delivery is 150 MKD and free from a 3,000 MKD product subtotal. Coverage and usual delivery time still need final confirmation.'],['Will I receive order updates?','When email is configured, customers receive order-received, shipped and delivered messages. The confirmation page also gives you an order reference.'],['Where is the store?','OutletX is in Dua Mall, Struga. It is open Monday to Saturday 09:00–21:00 and Sunday 10:00–20:00.']],
 mk:[['Дали големините на страницата се точни?','Страниците на производите ја прикажуваат најновата залиха што ја имаме. Залихата е ограничена и додавањето во кошничка не ја резервира. Повторно се проверува при нарачка.'],['Како да изберам големина?','Отворете го водичот, споредете со обувка што веќе ја носите или пратете ја шифрата и вашата вообичаена големина на Instagram.'],['Како се плаќа?','Плаќањето е во готово при достава. Страницата никогаш не бара податоци од картичка.'],['Колку чини доставата?','Доставата е 150 МКД и е бесплатна над 3.000 МКД. Подрачјето и вообичаеното време сè уште треба да се потврдат.'],['Дали ќе добијам известувања?','Кога е-поштата е конфигурирана, купувачот добива порака за примена, испратена и доставена нарачка. Страницата за потврда дава и референца.'],['Каде е продавницата?','OutletX е во Dua Mall, Струга. Работи понеделник–сабота 09:00–21:00 и недела 10:00–20:00.']],
 sq:[['A janë madhësitë në faqe të përditësuara?','Faqet e produkteve tregojnë stokun më të fundit që kemi. Stoku është i kufizuar dhe shtimi në shportë nuk e rezervon. Kontrollohet përsëri gjatë porosisë.'],['Si të zgjedh madhësinë?','Hapni udhëzuesin, krahasoni një këpucë që e mbani ose dërgoni kodin dhe madhësinë tuaj të zakonshme në Instagram.'],['Si paguaj?','Pagesa bëhet me para në dorëzim. Faqja nuk kërkon asnjëherë të dhëna të kartës.'],['Sa kushton dërgesa?','Dërgesa kushton 150 MKD dhe është falas mbi 3,000 MKD. Zona dhe koha e zakonshme ende duhet të konfirmohen.'],['A do të marr njoftime për porosinë?','Kur emaili është konfiguruar, klienti merr mesazhe kur porosia pranohet, dërgohet dhe dorëzohet. Faqja e konfirmimit jep edhe referencë.'],['Ku është dyqani?','OutletX është në Dua Mall, Strugë. Hapur hënë–shtunë 09:00–21:00 dhe të dielën 10:00–20:00.']]
};
export default function Help(){return <InfoPage title={title} description={description} path="/help">{({lang})=><><div className="faq-list">{q[lang].map(([question,answer])=><details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div><div className="help-links"><SiteLink href="/size-guide">Size guide →</SiteLink><SiteLink href="/shipping">Delivery & payment →</SiteLink><SiteLink href="/returns">Returns & exchanges →</SiteLink><SiteLink href="/contact">Contact OutletX →</SiteLink></div></>}</InfoPage>;}
