import InfoPage from '../components/InfoPage';
import SiteLink from '../components/SiteLink';
const title={en:'Returns & exchanges',mk:'Враќање и замена',sq:'Kthime dhe ndërrime'};
const description={en:'Check the latest return and exchange position before placing an order.',mk:'Проверете ги најновите информации за враќање и замена пред нарачка.',sq:'Kontrolloni informacionin e fundit për kthime dhe ndërrime para porosisë.'};
const copy={
 en:{heading:'The final policy is being prepared',text:'OutletX has not yet approved a final online returns and exchanges policy. We will not invent a time limit, fee or eligibility rule. Please contact the store before ordering if this affects your decision.',what:'When the policy is approved, this page will clearly explain:',list:['how many days a customer has','which condition, packaging and proof of purchase are required','whether discounted products are eligible','who pays return delivery','how exchanges, refunds and faulty products are handled'],cta:'Ask OutletX before ordering'},
 mk:{heading:'Конечната политика се подготвува',text:'OutletX сè уште нема одобрено конечна политика за онлајн враќање и замена. Нема да измислуваме рок, надомест или услов. Контактирајте ја продавницата пред нарачка ако ова влијае на вашата одлука.',what:'Кога политиката ќе биде одобрена, тука јасно ќе пишува:',list:['колку дена има купувачот','каква состојба, пакување и доказ за купување се потребни','дали производите на попуст важат','кој ја плаќа повратната достава','како се решаваат замена, рефундација и неисправни производи'],cta:'Прашајте го OutletX пред нарачка'},
 sq:{heading:'Politika përfundimtare po përgatitet',text:'OutletX ende nuk ka miratuar një politikë përfundimtare për kthimet dhe ndërrimet online. Nuk do të shpikim afat, tarifë ose kusht. Kontaktoni dyqanin para porosisë nëse kjo ndikon në vendimin tuaj.',what:'Kur politika të miratohet, kjo faqe do të shpjegojë qartë:',list:['sa ditë ka klienti','çfarë gjendjeje, paketimi dhe dëshmie blerjeje kërkohet','nëse vlejnë produktet me zbritje','kush paguan dërgesën e kthimit','si trajtohen ndërrimet, rimbursimet dhe produktet me defekt'],cta:'Pyetni OutletX para porosisë'}
};
export default function Returns(){return <InfoPage title={title} description={description} path="/returns">{({lang})=>{const c=copy[lang];return <><article className="policy-feature"><span>!</span><h2>{c.heading}</h2><p>{c.text}</p></article><article><h2>{c.what}</h2><ul>{c.list.map(x=><li key={x}>{x}</li>)}</ul></article><SiteLink className="store-button red" href="/contact">{c.cta} →</SiteLink></>;}}</InfoPage>;}
