import InfoPage from '../components/InfoPage';
import {useStore} from '../context/StoreContext';
import {money} from '../lib/catalogue';
const title={en:'Delivery & payment',mk:'Достава и плаќање',sq:'Dërgesa dhe pagesa'};
const description={en:'What is confirmed about ordering from OutletX today.',mk:'Што е потврдено за нарачување од OutletX во моментов.',sq:'Çfarë është konfirmuar për porositë nga OutletX sot.'};
const copy={
 en:{cost:'Delivery cost',costText:'Delivery is {fee}. It is free when the product subtotal is {free} or more.',pay:'Payment',payText:'Orders are paid in cash when delivered. OutletX does not ask for card details on this website.',coverage:'Delivery area and timing',coverageText:'The delivery area, courier and usual delivery time are still being finalised. Please ask OutletX before ordering if timing or location matters to you.',check:'Before accepting real orders, OutletX will publish the confirmed delivery area and usual working-day estimate here.'},
 mk:{cost:'Цена за достава',costText:'Доставата е {fee}. Бесплатна е кога меѓузбирот на производите е {free} или повеќе.',pay:'Плаќање',payText:'Нарачките се плаќаат во готово при достава. OutletX не бара податоци од картичка на оваа веб-страница.',coverage:'Подрачје и време на достава',coverageText:'Подрачјето, курирот и вообичаеното време на достава сè уште се утврдуваат. Прашајте го OutletX пред нарачка ако времето или локацијата ви се важни.',check:'Пред да започне со вистински нарачки, OutletX ќе ги објави потврденото подрачје и вообичаениот број работни денови.'},
 sq:{cost:'Kostoja e dërgesës',costText:'Dërgesa kushton {fee}. Është falas kur nëntotali i produkteve është {free} ose më shumë.',pay:'Pagesa',payText:'Porositë paguhen me para në dorëzim. OutletX nuk kërkon të dhëna të kartës në këtë faqe.',coverage:'Zona dhe koha e dërgesës',coverageText:'Zona, korrieri dhe koha e zakonshme e dërgesës janë ende duke u përcaktuar. Pyesni OutletX para porosisë nëse koha ose vendndodhja janë të rëndësishme.',check:'Para pranimit të porosive reale, OutletX do të publikojë këtu zonën dhe numrin e zakonshëm të ditëve të punës.'}
};
export default function Shipping(){const {content}=useStore();return <InfoPage title={title} description={description} path="/shipping">{({lang})=>{const c=copy[lang];const replace=s=>s.replace('{fee}',money(content.settings.deliveryFee)).replace('{free}',money(content.settings.freeDeliveryOver));return <><article><span>01</span><h2>{c.cost}</h2><p>{replace(c.costText)}</p></article><article><span>02</span><h2>{c.pay}</h2><p>{c.payText}</p></article><article><span>03</span><h2>{c.coverage}</h2><p>{c.coverageText}</p></article><aside className="notice-box">{c.check}</aside></>;}}</InfoPage>;}
