import InfoPage from '../components/InfoPage';
import SiteLink from '../components/SiteLink';
const title={en:'Terms of sale',mk:'Услови за продажба',sq:'Kushtet e shitjes'};
const description={en:'The confirmed ordering terms and the decisions still required before launch.',mk:'Потврдените услови за нарачка и одлуките потребни пред почеток.',sq:'Kushtet e konfirmuara dhe vendimet e nevojshme para fillimit.'};
const copy={
 en:[['Products and prices','Product pages show the current price in MKD, product code and available sizes. Outlet stock is limited. Adding to the bag does not reserve a product; the server checks availability when the order is placed.'],['Ordering and payment','An order is requested by submitting checkout details. Payment is cash on delivery and no card details are collected. The customer receives an on-screen reference; status emails depend on the store email service being configured.'],['Delivery','The current delivery charge is 150 MKD and it is free for product subtotals from 3,000 MKD. Delivery coverage, courier and the usual working-day estimate must be confirmed before real sales.'],['Returns and exchanges','A final returns, exchanges, faulty-products and refund policy has not yet been approved. Customers should not place a real order until those terms are published or individually confirmed with the store.'],['Business identity and final review','The registered business name, support email, applicable-law wording and policy effective date still need to be added and professionally reviewed before the online store accepts real customer orders.']],
 mk:[['Производи и цени','Страниците ги прикажуваат цената во МКД, шифрата и достапните големини. Залихата е ограничена. Додавањето во кошничка не резервира производ; достапноста се проверува при нарачка.'],['Нарачка и плаќање','Нарачката се поднесува преку формата. Плаќањето е во готово при достава и не се собираат податоци од картичка. Купувачот добива референца; е-поштата зависи од конфигурацијата.'],['Достава','Доставата е 150 МКД и бесплатна за меѓузбир од 3.000 МКД. Подрачјето, курирот и вообичаениот рок мора да се потврдат пред вистинска продажба.'],['Враќање и замена','Конечна политика за враќање, замена, неисправни производи и рефундација сè уште не е одобрена. Не треба да се прави вистинска нарачка пред тие услови да бидат објавени или потврдени со продавницата.'],['Деловен идентитет и проверка','Регистрираното име, е-поштата за поддршка, важечкото право и датумот на политиката треба да се додадат и стручно проверат пред почеток.']],
 sq:[['Produktet dhe çmimet','Faqet tregojnë çmimin në MKD, kodin dhe madhësitë në dispozicion. Stoku është i kufizuar. Shtimi në shportë nuk rezervon produktin; stoku kontrollohet gjatë porosisë.'],['Porosia dhe pagesa','Porosia kërkohet me formularin. Pagesa bëhet me para në dorëzim dhe nuk mblidhen të dhëna karte. Klienti merr referencë; emaili varet nga konfigurimi.'],['Dërgesa','Dërgesa kushton 150 MKD dhe është falas për nëntotal nga 3,000 MKD. Zona, korrieri dhe afati i zakonshëm duhet të konfirmohen para shitjeve reale.'],['Kthimet dhe ndërrimet','Politika përfundimtare për kthime, ndërrime, produkte me defekt dhe rimbursime nuk është miratuar. Porosi reale nuk duhet të bëhen para publikimit ose konfirmimit të kushteve me dyqanin.'],['Identiteti i biznesit dhe kontrolli','Emri i regjistruar, emaili mbështetës, formulimi i ligjit të zbatueshëm dhe data duhet të shtohen e të kontrollohen profesionalisht para fillimit.']]
};
export default function Terms(){return <InfoPage title={title} description={description} path="/terms">{({lang})=><>{copy[lang].map(([h,p],i)=><article key={h}><span>{String(i+1).padStart(2,'0')}</span><h2>{h}</h2><p>{p}</p></article>)}<SiteLink className="store-button" href="/contact">Contact OutletX →</SiteLink></>}</InfoPage>;}
