import { useEffect,useRef,useState } from 'react';
import { useRouter } from 'next/router';
import { useCart } from '../../context/CartContext';
import { useStore } from '../../context/StoreContext';

const nav=[['Men','/products?gender=men'],['Women','/products?gender=women'],['Kids','/products?gender=kids'],['Shoes','/products?category=shoes'],['Sale','/products?sort=discount']];

export default function StoreLayout({children}){const { products, content, loading, error } = useStore();const router=useRouter();const{cartCount,setCartOpen}=useCart();const[menu,setMenu]=useState(false);const[searchOpen,setSearchOpen]=useState(false);const[query,setQuery]=useState('');const searchRef=useRef(null);const results=query.trim().length>1?products.filter((p)=>`${p.brand} ${p.name} ${p.sku}`.toLowerCase().includes(query.toLowerCase())).slice(0,5):[];useEffect(()=>{setMenu(false);setSearchOpen(false);},[router.asPath]);const submit=(e)=>{e.preventDefault();if(query.trim())router.push(`/products?search=${encodeURIComponent(query.trim())}`);};return <div className="store-shell"><div className="store-announcement"><span>Authentic brands</span><b>Free delivery from {content.settings.freeDeliveryOver.toLocaleString()} MKD</b><span>{content.settings.address}</span></div><header className="store-header"><div className="store-header-main"><a className="store-logo" href="/">OUTLET<span>X</span></a><nav className="store-nav" aria-label="Main navigation">{nav.map(([label,href])=><a key={label} href={href}>{label}</a>)}</nav><div className="store-actions"><button aria-label="Search" onClick={()=>setSearchOpen(!searchOpen)}>⌕</button><button aria-label={`Open cart with ${cartCount} items`} className="store-cart-button" onClick={()=>setCartOpen(true)}>Bag{cartCount>0&&<b>{cartCount}</b>}</button><button className="store-menu-button" aria-label="Open menu" onClick={()=>setMenu(!menu)}>☰</button></div></div>{(searchOpen||menu)&&<div className="store-header-drawer">{searchOpen&&<div className="store-search" ref={searchRef}><form onSubmit={submit}><input autoFocus value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search shoes, brands, or product codes…" aria-label="Search products"/><button>Search</button></form>{results.length>0&&<div className="store-search-results">{results.map((p)=><a key={p.id} href={`/product/${p.id}`}><img src={p.images[0]} alt=""/><span><b>{p.brand} {p.name}</b><small>{p.newPrice.toLocaleString()} MKD</small></span></a>)}</div>}</div>}{menu&&<nav className="store-mobile-nav">{nav.map(([label,href])=><a key={label} href={href}>{label}<span>→</span></a>)}<a href="/about">About<span>→</span></a><a href="/contact">Contact<span>→</span></a></nav>}</div>}</header><main>{error?<div role="alert" className="checkout-error">{error} Please refresh or message the store.</div>:loading?<p role="status" style={{padding:24}}>Loading the latest products…</p>:children}</main><TrustStrip/><StoreFooter/></div>}

export function TrustStrip(){const {content} = useStore();return <section className="store-trust"><div><b>Authentic products</b><span>Carefully sourced branded stock</span></div><div><b>Cash on delivery</b><span>Pay when your order arrives</span></div><div><b>Store support</b><span>Message {content.settings.instagram}</span></div><div><b>Easy size help</b><span>Clear sizing on every product</span></div></section>}

export function StoreFooter(){const {content} = useStore();const settings = content.settings;return <footer className="store-footer"><div className="store-footer-main"><div className="store-footer-about"><a className="store-logo light" href="/">OUTLET<span>X</span></a><p>Authentic branded sportswear at real outlet prices. Visit us at Dua Mall, Struga.</p><a className="store-instagram" href={`https://instagram.com/${encodeURIComponent(settings.instagram.replace(/^@/, ""))}`} target="_blank" rel="noopener noreferrer">{settings.instagram} ↗</a></div><div><h3>Shop</h3>{nav.map(([label,href])=><a key={label} href={href}>{label}</a>)}</div><div><h3>Help</h3><a href="/contact">Contact us</a><a href="/about">About OutletX</a><a href="/contact#hours">Opening hours</a><a href="/contact#location">Store location</a></div><div><h3>Visit</h3><p>{settings.address}<br/>{settings.country}</p><p>Mon–Sat {settings.openingHours.weekdays}<br/>Sunday {settings.openingHours.sunday}</p></div></div><div className="store-footer-bottom"><span>© {new Date().getFullYear()} OutletX</span><span>Authentic brands · Outlet prices</span></div></footer>}
